name: Update ECS Fargate Service

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
      
      - name: Install dependencies
        run: npm install
      
      - name: Build and push Docker image
        run: |
          # Build your Docker image and tag it appropriately
          docker build -t 044101166930.dkr.ecr.us-east-1.amazonaws.com/repository-861579c:latest ./apps/next
          # Configure AWS CLI with the provided secrets
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set aws_region us-east-1
          # Authenticate Docker with ECR
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 044101166930.dkr.ecr.us-east-1.amazonaws.com/repository-861579c-url
          # Push the image to ECR
          docker push 044101166930.dkr.ecr.us-east-1.amazonaws.com/repository-861579c:latest
      
      - name: Update ECS service
        run: |
          # Use AWS CLI to update the ECS service with the latest image
          aws ecs update-service --cluster cluster-898f574 --service service-a44dd02 --force-new-deployment
