name: Update ECS Fargate Service

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14  # Adjust the Node.js version as needed
      
      - name: Install dependencies
        run: npm install
      
      - name: Build and push Docker image
        run: |
          # Build your Docker image and tag it appropriately
          docker build -t your-ecr-repo:latest .
          # Configure AWS CLI with the provided secrets
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # Authenticate Docker with ECR
          aws ecr get-login-password --region your-aws-region | docker login --username AWS --password-stdin your-ecr-repo-url
          # Push the image to ECR
          docker push your-ecr-repo:latest
      
      - name: Update ECS service
        run: |
          # Use AWS CLI to update the ECS service with the latest image
          aws ecs update-service --cluster your-cluster-name --service your-service-name --force-new-deployment
